### ISSUE TITLE
Wait if the namespace we are monitoring doesn't exist (yet)

### ISSUE THREAD

**Issue by guidoiaquinti** [jupyterhub/action-k8s-await-workloads#38]
First of all, thank you for this GitHub action! 👏  

### Bug description
Maybe this is by design but the action doesn't seems to wait if the namespace we are monitoring doesn't exist

#### Expected behaviour
The action should wait till the namespace and its resources are ready.

#### Actual behaviour
The action doesn't wait if the namespace doesn't exist

### Your personal set up
GitHub action config:
```
    - name: Wait until all the resources are fully deployed in k8s
      uses: jupyterhub/action-k8s-await-workloads@main
      with:
        namespace: "posthog"
        workloads: "" # all
        timeout: 600
        max-restarts: 15
```

GitHub action logs:
```
Run jupyterhub/action-k8s-await-workloads@main
  with:
    namespace: posthog
    timeout: 600
    max-restarts: 15

Awaiting workloads
================================================================================
Settings:
- workloads: 
- namespace: posthog
- timeout: 600
- max-restarts: 15

Workload overview
--------------------------------------------------------------------------------
/usr/local/bin/kubectl get ds,deploy,sts --namespace=posthog
No resources found in posthog namespace.

Workloads awaited
--------------------------------------------------------------------------------

All workloads awaited!
--------------------------------------------------------------------------------
```
</details>
